[package]
name = "boomwhackers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
elementtree = "0.7"
index_vec = "0.1"
itertools = "0.10"
ordered-float = "3.0"
rand = "0.8"
rand_chacha = "0.3"
zip = "0.6"
